version: '3'
services:
  allerta-updater:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - mongodb
    environment:
      DB: mongodb://mongodb:27017/allerta_meteo
    networks:
      - app-network
    ports:
      - "8080:8080" # Espone la porta 27017 dell'host sulla porta 27017 del container


  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017" # Espone la porta 27017 dell'host sulla porta 27017 del container
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:
    driver: local

networks:
  app-network:
    driver: bridge
